# Generated by Django 3.0.8 on 2020-07-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('recommender', models.CharField(max_length=255)),
                ('source', models.URLField()),
                ('amazon_link', models.URLField()),
                ('description', models.CharField(max_length=255)),
                ('rec_type', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
                ('publish_year', models.CharField(max_length=255)),
                ('on_list', models.CharField(max_length=255)),
                ('review_excerpt', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('title', 'author', 'recommender')},
            },
        ),
    ]
